### ISSUE TITLE
error al recuperar struct desde un stack

### ISSUE THREAD

**Issue by naim2206** [naim2206/proyecto_ajedrez#15]
que onda josean, en nuestro proyecto estamos usando stacks para el botón de undo, pero al momento de recuperar una struct del stack no se guarda correctamente.

```
void goBack(Game* g, int board[8][8], Stack* s)
{
    if (s->top->prior != NULL)
    {
        pop(s);
        if (s->top != NULL)
        {
            g = s->top->g;
            for (int i = 0; i < 8; i++)
                for (int j = 0; j < 8; j++)
                    board[i][j] = s->top->board[i][j];
        }
    }
}
```

En esta función, se actualizan nuestos valores del board pero la struct game (g) no cambia a el valor del top del stack.

**Comment by DevCam** [comment]
la linea: 
`g = s->top->g;` 
no tiene ningun efecto en el resto del programa, si deseamos modificar nuestro game tendriamos que:

a) pasar un doble apuntador
b) modificar el CONTENIDO del apuntador g.

@naim2206 @XRemi300 
Como copiar direcciones de memoria suele llevar a bugs dificiles de reparar, me inclinaria personalmente por la opción b.
